name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git config
        run: |
          git config --global user.email "shalini988shalu@gmail.com"
          git config --global user.name "Shal3"

      - name: Add Hugging Face remote and push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://shal1993:${HF_TOKEN}@huggingface.co/spaces/shal1993/Search_Engine_LLM || true
          git push hf main --force
